# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: MyVariables
  - name: NODE_VERSION
    value: '22.x' 

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(NODE_VERSION)
  displayName: 'Install Node.js $(NODE_VERSION)'

- script: |
    cd server
    npm install
    npm test
  displayName: 'Functional Tests: Server'


- script: |
    cd client
    npm install
    npm test
  displayName: 'Functional Tests: Client'


- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/test-results/*.xml' 
  displayName: 'Publish Functional Test Results'


- script: |
    cd server
    npm audit --audit-level=high
  displayName: 'Non-functional: Security Scan (Server)'
  continueOnError: true 


- script: |
    cd client
    npm run build
  displayName: 'Build client'


- task: CopyFiles@2
  inputs:
    SourceFolder: 'client/build'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy Files to Staging'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifact'

- task: Docker@2
  displayName: 'Build and Push Docker Image'
  inputs:
    containerRegistry: 'MyDockerHub'  
    repository: 'nhyusein/todo-app'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest