# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: MyVariables

  - name: NODE_VERSION
    value: '22.x' 

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(NODE_VERSION)
  displayName: 'Install Node.js $(NODE_VERSION)'

- script: |
    npm install
    npm run build
  workingDirectory: client
  displayName: 'Install and Build client'

- script: node --version
  displayName: 'Verify Node version'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'client/build'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy Files to Staging'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifact'